#=========================================================
# Base settings
#=========================================================
# url: https://basharbuddha.github.io
baseurl: /
title: 巴夏影音訊息彙集
description: 👽


#=========================================================
# Nav list
#=========================================================
nav_lists:
  - titles:
      en: About
      zh: 关于
      zh-Hans: 关于
      zh-Hant: 關於
    url: /about.html
  - titles:
      en: Search
      zh: 搜索
      zh-Hans: 搜索
      zh-Hant: 搜尋
    url: /search.html


#=========================================================
# Language & timezone
#=========================================================
lang: zh-Hant
timezone: Asia/Taipei


#=========================================================
# Author & social
#=========================================================
author:
  name: Bashar.Buddha
  # email:  bashar.buddha@gmail.com
  # facebook:  #your Facebook username
  # twitter:  #your Twitter username
  # github:  #your GitHub username


#=========================================================
# Disqus
#=========================================================
disqus:
  shortname: basharbuddha


#=========================================================
# Google Analytics
#=========================================================
ga_tracking_id:  UA-112164871-1


#=========================================================
# LeanCloud
#=========================================================
leancloud:
  app_id: 3sBjcT3E45n9zVghcgQnc0T5-MdYXbMMI
  app_key: x5Sx0wvrYtDrKupVzvxPbKEE
  app_class: Counter


#=========================================================
# Paginate
#=========================================================
paginate: 10
paginate_path: /posts/page:num


#=========================================================
# Post excerpts
#=========================================================
excerpt_separator: <!--more-->
excerpt_type: text # text | html


#=========================================================
# Build
#=========================================================
markdown: kramdown
highlighter: rouge
permalink: date
exclude:
  - CHANGELOG.md
  - CHECKLIST.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor
  - .sass-cache


#=========================================================
# Plugins
#=========================================================
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji


#=========================================================
# Algolia
#=========================================================
algolia:
  application_id: VXNUMUQ10M
  index_name: basharbuddha
  search_only_api_key: 2454842b9872cfac31e11c2427623f10
  nodes_to_index: 'p'
  files_to_exclude:
    - about.md
    - search.html
    - all.html
    - 404.html


#=========================================================
# Development
#=========================================================
isdebug: false
